const fs = require('fs');

const stations = [
    { "code": "NDLS", "name": "New Delhi", "city": "Delhi", "state": "Delhi" },
    { "code": "CSMT", "name": "Chhatrapati Shivaji Maharaj Terminus", "city": "Mumbai", "state": "Maharashtra" },
    { "code": "HWH", "name": "Howrah Junction", "city": "Kolkata", "state": "West Bengal" },
    { "code": "MAS", "name": "Chennai Central", "city": "Chennai", "state": "Tamil Nadu" },
    { "code": "SBC", "name": "KSR Bengaluru", "city": "Bangalore", "state": "Karnataka" },
    { "code": "PNBE", "name": "Patna Junction", "city": "Patna", "state": "Bihar" },
    { "code": "LKO", "name": "Lucknow Charbagh", "city": "Lucknow", "state": "Uttar Pradesh" },
    { "code": "CNB", "name": "Kanpur Central", "city": "Kanpur", "state": "Uttar Pradesh" },
    { "code": "ALD", "name": "Allahabad Junction", "city": "Allahabad", "state": "Uttar Pradesh" },
    { "code": "BSB", "name": "Varanasi Junction", "city": "Varanasi", "state": "Uttar Pradesh" },
    { "code": "JP", "name": "Jaipur Junction", "city": "Jaipur", "state": "Rajasthan" },
    { "code": "ADI", "name": "Ahmedabad Junction", "city": "Ahmedabad", "state": "Gujarat" },
    { "code": "PUNE", "name": "Pune Junction", "city": "Pune", "state": "Maharashtra" },
    { "code": "SC", "name": "Secunderabad Junction", "city": "Hyderabad", "state": "Telangana" },
    { "code": "BZA", "name": "Vijayawada Junction", "city": "Vijayawada", "state": "Andhra Pradesh" },
    { "code": "NGP", "name": "Nagpur Junction", "city": "Nagpur", "state": "Maharashtra" },
    { "code": "BPL", "name": "Bhopal Junction", "city": "Bhopal", "state": "Madhya Pradesh" },
    { "code": "INDB", "name": "Indore Junction", "city": "Indore", "state": "Madhya Pradesh" },
    { "code": "GHY", "name": "Guwahati", "city": "Guwahati", "state": "Assam" },
    { "code": "ASR", "name": "Amritsar Junction", "city": "Amritsar", "state": "Punjab" },
    { "code": "LDH", "name": "Ludhiana Junction", "city": "Ludhiana", "state": "Punjab" },
    { "code": "CDG", "name": "Chandigarh", "city": "Chandigarh", "state": "Chandigarh" },
    { "code": "DLI", "name": "Old Delhi", "city": "Delhi", "state": "Delhi" },
    { "code": "NZM", "name": "Hazrat Nizamuddin", "city": "Delhi", "state": "Delhi" },
    { "code": "ANVT", "name": "Anand Vihar Terminal", "city": "Delhi", "state": "Delhi" },
    { "code": "BCT", "name": "Mumbai Central", "city": "Mumbai", "state": "Maharashtra" },
    { "code": "LTT", "name": "Lokmanya Tilak Terminus", "city": "Mumbai", "state": "Maharashtra" },
    { "code": "BDTS", "name": "Bandra Terminus", "city": "Mumbai", "state": "Maharashtra" },
    { "code": "SDAH", "name": "Sealdah", "city": "Kolkata", "state": "West Bengal" },
    { "code": "KOAA", "name": "Kolkata", "city": "Kolkata", "state": "West Bengal" },
    { "code": "MS", "name": "Chennai Egmore", "city": "Chennai", "state": "Tamil Nadu" },
    { "code": "YPR", "name": "Yesvantpur Junction", "city": "Bangalore", "state": "Karnataka" },
    { "code": "TVC", "name": "Thiruvananthapuram Central", "city": "Thiruvananthapuram", "state": "Kerala" },
    { "code": "ERS", "name": "Ernakulam Junction", "city": "Kochi", "state": "Kerala" },
    { "code": "CBE", "name": "Coimbatore Junction", "city": "Coimbatore", "state": "Tamil Nadu" },
    { "code": "MDU", "name": "Madurai Junction", "city": "Madurai", "state": "Tamil Nadu" },
    { "code": "TPTY", "name": "Tirupati", "city": "Tirupati", "state": "Andhra Pradesh" },
    { "code": "VSKP", "name": "Visakhapatnam", "city": "Visakhapatnam", "state": "Andhra Pradesh" },
    { "code": "BBS", "name": "Bhubaneswar", "city": "Bhubaneswar", "state": "Odisha" },
    { "code": "PURI", "name": "Puri", "city": "Puri", "state": "Odisha" },
    { "code": "RNC", "name": "Ranchi Junction", "city": "Ranchi", "state": "Jharkhand" },
    { "code": "TATA", "name": "Tatanagar Junction", "city": "Jamshedpur", "state": "Jharkhand" },
    { "code": "RPR", "name": "Raipur Junction", "city": "Raipur", "state": "Chhattisgarh" },
    { "code": "JAT", "name": "Jammu Tawi", "city": "Jammu", "state": "Jammu & Kashmir" },
    { "code": "SVDK", "name": "SMVD Katra", "city": "Katra", "state": "Jammu & Kashmir" },
    { "code": "DDN", "name": "Dehradun", "city": "Dehradun", "state": "Uttarakhand" },
    { "code": "HW", "name": "Haridwar", "city": "Haridwar", "state": "Uttarakhand" },
    { "code": "MB", "name": "Moradabad", "city": "Moradabad", "state": "Uttar Pradesh" },
    { "code": "BE", "name": "Bareilly", "city": "Bareilly", "state": "Uttar Pradesh" },
    { "code": "GKP", "name": "Gorakhpur Junction", "city": "Gorakhpur", "state": "Uttar Pradesh" }
];

const trains = [
    { "trainNumber": "12951", "trainName": "Mumbai Rajdhani Express", "source": "MMCT", "destination": "NDLS", "runningDays": "Mon, Tue, Wed, Thu, Fri, Sat, Sun" },
    { "trainNumber": "12953", "trainName": "August Kranti Rajdhani Express", "source": "MMCT", "destination": "NZM", "runningDays": "Mon, Tue, Wed, Thu, Fri, Sat, Sun" },
    { "trainNumber": "12301", "trainName": "Howrah Rajdhani Express", "source": "HWH", "destination": "NDLS", "runningDays": "Mon, Tue, Wed, Thu, Fri, Sat" },
    { "trainNumber": "12309", "trainName": "Rajendra Nagar Patna Rajdhani Express", "source": "RJPB", "destination": "NDLS", "runningDays": "Mon, Tue, Wed, Thu, Fri, Sat, Sun" },
    { "trainNumber": "12431", "trainName": "Trivandrum Rajdhani Express", "source": "TVC", "destination": "NZM", "runningDays": "Tue, Thu, Fri" },
    { "trainNumber": "12433", "trainName": "Chennai Rajdhani Express", "source": "MAS", "destination": "NZM", "runningDays": "Fri, Sun" },
    { "trainNumber": "12003", "trainName": "New Delhi Lucknow Swarna Shatabdi", "source": "LKO", "destination": "NDLS", "runningDays": "Mon, Tue, Wed, Thu, Fri, Sat, Sun" },
    { "trainNumber": "12005", "trainName": "Kalka Shatabdi Express", "source": "NDLS", "destination": "KLK", "runningDays": "Mon, Tue, Wed, Thu, Fri, Sat, Sun" },
    { "trainNumber": "12009", "trainName": "Mumbai Central Ahmedabad Shatabdi", "source": "MMCT", "destination": "ADI", "runningDays": "Mon, Tue, Wed, Thu, Fri, Sat" },
    { "trainNumber": "22439", "trainName": "Vande Bharat Express", "source": "NDLS", "destination": "SVDK", "runningDays": "Mon, Wed, Thu, Fri, Sat, Sun" },
    { "trainNumber": "22436", "trainName": "Vande Bharat Express", "source": "NDLS", "destination": "BSB", "runningDays": "Tue, Wed, Thu, Fri, Sat, Sun" },
    { "trainNumber": "12801", "trainName": "Purushottam Express", "source": "PURI", "destination": "NDLS", "runningDays": "Mon, Tue, Wed, Thu, Fri, Sat, Sun" },
    { "trainNumber": "12137", "trainName": "Punjab Mail", "source": "CSMT", "destination": "FZR", "runningDays": "Mon, Tue, Wed, Thu, Fri, Sat, Sun" },
    { "trainNumber": "12860", "trainName": "Gitanjali Express", "source": "HWH", "destination": "CSMT", "runningDays": "Mon, Tue, Wed, Thu, Fri, Sat, Sun" },
    { "trainNumber": "12615", "trainName": "Grand Trunk Express", "source": "MAS", "destination": "NDLS", "runningDays": "Mon, Tue, Wed, Thu, Fri, Sat, Sun" },
    { "trainNumber": "12269", "trainName": "Duronto Express", "source": "MAS", "destination": "NZM", "runningDays": "Mon, Fri" },
    { "trainNumber": "12259", "trainName": "Sealdah Bikaner Duronto", "source": "SDAH", "destination": "BKN", "runningDays": "Mon, Wed, Thu, Sun" },
    { "trainNumber": "12903", "trainName": "Golden Temple Mail", "source": "MMCT", "destination": "ASR", "runningDays": "Mon, Tue, Wed, Thu, Fri, Sat, Sun" },
    { "trainNumber": "12627", "trainName": "Karnataka Express", "source": "SBC", "destination": "NDLS", "runningDays": "Mon, Tue, Wed, Thu, Fri, Sat, Sun" },
    { "trainNumber": "12839", "trainName": "Chennai Mail", "source": "HWH", "destination": "MAS", "runningDays": "Mon, Tue, Wed, Thu, Fri, Sat, Sun" },
    { "trainNumber": "12702", "trainName": "Hussainsagar Express", "source": "HYB", "destination": "CSMT", "runningDays": "Mon, Tue, Wed, Thu, Fri, Sat, Sun" },
    { "trainNumber": "12621", "trainName": "Tamil Nadu Express", "source": "MAS", "destination": "NDLS", "runningDays": "Mon, Tue, Wed, Thu, Fri, Sat, Sun" },
    { "trainNumber": "12141", "trainName": "Patliputra Express", "source": "LTT", "destination": "PPTA", "runningDays": "Mon, Tue, Wed, Thu, Fri, Sat, Sun" },
    { "trainNumber": "12311", "trainName": "Netaji Express", "source": "HWH", "destination": "KLK", "runningDays": "Mon, Tue, Wed, Thu, Fri, Sat, Sun" },
    { "trainNumber": "12723", "trainName": "Telangana Express", "source": "HYB", "destination": "NDLS", "runningDays": "Mon, Tue, Wed, Thu, Fri, Sat, Sun" },
    { "trainNumber": "12915", "trainName": "Ashram Express", "source": "ADI", "destination": "DLI", "runningDays": "Mon, Tue, Wed, Thu, Fri, Sat, Sun" },
    { "trainNumber": "12417", "trainName": "Prayagraj Express", "source": "PRYJ", "destination": "NDLS", "runningDays": "Mon, Tue, Wed, Thu, Fri, Sat, Sun" },
    { "trainNumber": "12555", "trainName": "Gorakhdham Express", "source": "GKP", "destination": "BHI", "runningDays": "Mon, Tue, Wed, Thu, Fri, Sat, Sun" },
    { "trainNumber": "12981", "trainName": "Chetak Express", "source": "DEE", "destination": "UDZ", "runningDays": "Mon, Tue, Wed, Thu, Fri, Sat, Sun" },
    { "trainNumber": "12245", "trainName": "Howrah Yesvantpur Duronto", "source": "HWH", "destination": "YPR", "runningDays": "Tue, Wed, Fri, Sat, Sun" }
];

fs.mkdirSync('data', { recursive: true });
fs.writeFileSync('data/stations.json', JSON.stringify(stations, null, 2));
fs.writeFileSync('data/trains.json', JSON.stringify(trains, null, 2));
console.log('Local datasets created successfully!');
